
label start:
    scene bg inicio
    with dissolve
    play music "audio/bossa.mp3"

    show silveira comum at left
    with dissolve
    show estevao comum at right
    with dissolve
    Silveira comum "Curaganga, Matinta, mortalha, lobsomem... No fim tudo isso é uma farça para atiçar medo nos mais ingênuos."
    Silveira "Mula sem cabeça? Que grande piada! Quem não deve ter cabeça é quem acredita de fato em tais asneiras."
    Silveira "É o que sempre lhe digo, Senhor Estevão. Tu tem meu prestígio, logo preciso lhe alertar das artimanhas dos malandros, e que repito: não são poucas meu caro!"
    Estevao comum  "Eu poderia concordar com o Dr. Silveira se o meu eu de hoje não soubesse o que sabe as más línguas!"
    Silveira "Ora, Estevão. O que é isso agora? Não me venha com meia palavra! Se acha que estou errado desembucha logo e termine essa sua idéia descabida."
    Estevao  "Sou alguém que respeita as lendas e tradições. Não mais hajo de má amigabilidade com o que os mais antigos repassam para minha pessoa."
    Estevao  "O que quero dizer, Dr. Silveira, é que por grande tempo eu fui essa gente de pouco crença que nem o senhor até o dia em que me foi contada a história do velho tio de minha amada esposa, o tenente Antônio de Sousa."
    Estevao   "O tenente Antônio de Sousa era um desses moços que se gabam de não crer em nada, que zombam das coisas mais sérias e riem dos santos e dos milagres..."
    nvle "Costumava dizer que isso de almas do outro mundo era uma grande mentira." 
    nvle "Que só os tolos temem o lobisomem e feiticeiras."
    nvle "Jurava ser capaz de dormir uma noite inteira dentro do cemitério,"
    nvle"e até de pas-sear às dez horas pela frente da casa do judeu, em sexta-feira maior."
    nvle "Quando a gente se habitua a venerar os decretos da Providência, "
    nvle "sob qualquer forma que se manifestem,"
    nvle "quando a gente chega à idade avançada em que a lição"
    nvle "da experiência demonstra a verdade do que os"
    nvle"avós vi-ram e contaram,"
    nvle "custa ouvir com paciência os sarcasmos com que os moços tentam ridicularizar"
    nvle "as mais respeitáveis tradi-ções, levados por uma vaidade tola,"
    nvle "pelo desejo de parecerem espíritos fortes,"
    nvle"como dizia o Dr. Rebelo."
    nvle "Peço sempre a Deus que me livre de semelhante tentação. "
    nvle "Acredito no que vejo e no que me contam pessoas fidedignas,"
    nvle "por mais extraordinário que pareça."
    nvle "Sei que o poder do Criador é infinito e a arte do inimigo vária."
    nvle "Mas o tenente Sousa pensava de modo contrário!"
    nvle "Apontava à lua com o dedo, deixava-se ficar deitado quando passava um enterro,"
    nvle "não se benzia ouvindo o canto da morta-lha, dormia sem camisa, ria-se do trovão!"
    nvle "Alardeava o ardente desejo de encontrar um curupira, "
    nvle"um lobisomem"
    nvle"ou uma fei-ticeira."
    nvle "Ficava impassível vendo cair uma estrela e achava graça ao canto agoureiro do acauã,"
    nvle"que tantas desgraças oca-siona. Enfim, ao encontrar um agouro, sorria"
    nvle"e passava tranquilamente sem tirar da boca o seu cachimbo de verdadeira espuma do mar."
    show estevao falando at right
    with dissolve
    Estevao falando "Quereis saber uma coisa? Filho meu não frequentaria esses colégios e academias"
    nvle "onde só se aprende o desrespeito da religião."
    Estevao "Em Belém, parece que todas as crenças velhas vão pela água abaixo. A tal civilização tem acabado com tudo que tínhamos de bom."
    Estevao "A mocidade imprudente e leviana afasta-se dos princípios que os pais lhe incutiram no berÃ§o, lisonjeando-se duma falsa ciÃªncia que nada explica, e a que, mais acertada-mente, se chamaria charlatanismo."
    Estevao "Os maus livros, os livros novos, cheios de mentiras, são devorados avidamente. As coi-sas sagradas, os mistérios são cobertos de motejos, e, em uma palavra, a mocidade hoje, como o tenente Sousa, proclama alto que não crê no diabo (salvo seja, que lá me escapou a palavra!), nem nos agouros, nem nas feiticeiras, nem nos milagres."
    Estevao "O infeliz Antônio de Sousa, transviado por esses propaga-dores do mal, foi vítima de sua leviandade ainda não há muito tempo."
    nvle "Tendo por falta de meios abandonado o estudo da medicina, "
    nvle"veio Antônio de Sousa para a província em 1871 e conseguiu entrar como oficial do corpo de polícia."
    nvle"No ano seguinte, era promovido ao posto de tenente e nomeado delegado de Óbidos,"
    nvle"onde antes nunca tivera vindo."
    nvle "O seu gênio folgazão, sua urbanidade e delicadeza para com todos,"
    nvle "o seu respeito pela lei e pelo direito do cidadão faziam dele uma autoridade"
    nvle"como poucas temos tido."
    nvle "Seria um moço estimável a todos os respeitos,"
    nvle "se não fora a desgraçada mania de duvidar de tudo,"
   
    play music "audio/detective.mp3"
    scene bg rio de janeiro
    with dissolve
    nvle "que adquirira nas rodas de estudantes e de gazeteiros do Rio de Janeiro e do Pará."
    Estevao comum "Desde que lhe descobri esse lastimável defeito, previ que a história dele não acabaria bem."
    Estevao "Ides ver como se realizaram as minhas previsões."
   
    scene bg cabana 
    with dissolve
    show antonio serio at left
    with dissolve
    nvle "Em princípio de fevereiro de 1873, por ocasião do assassinato de João Torres,"
    nvle"no Paranamiri de cima, Antônio de Sousa para ali partiu, em diligência policial."
    nvle "Realizada a prisão do criminoso, a convite do Ribeiro,"
    nvle "que é o maior fazendeiro do Paranamiri, resolveu o tenente delegado lá passar alguns dias,"
    nvle "a fim de conhecer, disse ele, a vida íntima do lavrador da beira do rio."
    nvle "Não vos descreverei o sítio do tenente Ribeiro,"
    nvle "porque ninguém há em Óbidos que o não conheça,"
    nvle "principalmente daquela grande demanda que ele venceu contra Miguel Faria,"
    play sound "audio/passaro.mp3"
    nvle "por causa das terras do Uricurizal."
    nvle "Basta lembrar que todos os cacauais do Paranamiri se comunicam"
    nvle "entre si por uma vereda mal determinada, e que é fácil percorrer"
    nvle "uma grande extensão do caminho, vindo de sítio em sítio até a costa fronteira à cidade."
    nvle "Antônio de Sousa passava o tempo a visitar os sítios de cacau,"
    nvle "conversando com os moradores, a quem ouvia casos extraordinários,"
    nvle "ali sucedidos e zombando das crenças do povo."
   
    play music "audio/mystryForest.mp3"
    nvle "Como lhe falassem muitas vezes da Maria Mucoim,"
    nvle "afamada feiticeira daqueles arredores,"
    nvle "mostrava grande curiosidade de a conhecer."
    nvle "Um dia em que caçava papagaios, com Ribeiro,"
    nvle "contou o desejo que tinha de ver aquela célebre mulher,"
    nvle "cujo nome causa o maior terror em todo o distrito. O Ribeiro olhou para ele, admirado,"
    nvle "e depois de uma pausa disse:"
    show ribeiro comum at right
    with dissolve
    Ribeiro comum "Como? Não conhece Maria Mucoim? Pois olhe, ali a tem."
    nvle "E apontou para uma velha que, a pequena distância deles, apanhava galhos secos."
    nvle "O tenente Sousa viu na Maria Mucoim uma velhinha magra, alquebrada,"
    nvle "com uns olhos pequenos, de olhar sinistro, as maçãs do rosto muito salientes,"
    nvle "a boca negra, que, quando se abria num sorriso horroroso, deixava ver um dente,"
    nvle "um só!,"
    nvle "comprido e escuro."
    nvle "A cara cor de cobre, os cabelos amarelados"
    nvle "presos ao alto da cabeça por um trepa-moleque de tartaruga,"
    nvle" tinham um aspecto medonho que não consigo descrever."
    nvle "A feiticeira trazia ao pescoço um cordão sujo,"
    nvle "de onde pendiam numerosos bentinhos, falsos, já se vê,"
    nvle "com que procurava enganar ao próximo, para ocultar a sua verdadeira natureza."
    nvle "Quem não reconhece à primeira vista essas criaturas malditas"
    nvle "que fazem pacto com o inimigo e vivem de suas sortes más,"
    nvle "permitidas por Deus para castigo dos nossos pecados?"
    nvle "A Maria Mucoim,"
    nvle "segundo dizem más línguas"
    nvle" (que eu nada afirmo nem quero afirmar, pois só desejo dizer a verdade para o bem-estar da minha alma),"
    nvle"fora outrora caseira do defunto padre João, vigário de Óbidos."
    nvle "Depois que o reverendo foi dar contas a Deus do que fizera cá no mundo "
    nvle "(e severas deviam ser, segundo se dizia),"
    nvle "a tapuia retirou-se para o Paranamiri, onde,"
    nvle "em vez de cogitar em purgar os seus grandes pecados,"
    nvle "começou a exercer o hediondo ofício que sabeis,"
    nvle "naturalmente pela certeza de já estar condenada em vida."
    nvle "Quem nada pode esperar do céu, pede auxílio às profundas do inferno."
    nvle "E se isto digo, não por leviandade o menciono."
    nvle "Pessoas respeitáveis afirmaram-me ter visto a tapuia transformada em pata,"
    nvle "quando é indubitável que Mucoim jamais criou aves dessa espécie."
    nvle "Mas o Antônio de Sousa é que não acreditava nessas toleimas."
    nvle "Por isso atreveu-se a caçoar da feiticeira:"


    scene bg cabana
    with dissolve
    play music "audio/spooky.mp3"
    show antonio serio at left
    with dissolve
    show feiticeira seria at right
    with dissolve
    Tenente comum "Então, tia velha, é certo que você tem pacto com o diabo?"
    play sound "audio/disgusting.mp3"
    nvle "Lá me escapou a palavra maldita..."
    nvle "Mas foi para referir o caso tal como se passou."
    nvle "Deus me perdoe."
    Feiticeira seria "(...)"
    play sound "audio/disgusting.mp3"
    nvle "A tapuia não respondeu, mas pôs-se a olhar para ele com aqueles olhos sem luz"
    nvle "que intimidam aos mais corajosos pescadores da beira do rio."
    nvle"O rapaz insistiu, admirando o silêncio da velha."
    play sound "audio/footsteps.mp3"
    Tenente "É sério que você é feiticeira?"
    play sound "audio/jellyroll.mp3"
    nvle "O demônio da mulher continuou calada e, "
    nvle "levantando um feixe de lenha, pôs-se a caminhar com passos trôpegos."
    nvle "Logo Souza impacientou-se."

    show tenente apreensivo at left
    with dissolve
    Tenente apreensivo "Falas ou não, mulher do..."
    play sound "audio/FearOfTheDark.mp3"
    nvle "Como moço de agora, o tenente gastava muito o nome do"
    nvle "inimigo do gênero humano"
    nvle "Os lábios da velha arregaçaram-se, deixando ver o único dente. "
    nvle "Ela lançou ao rapaz um olhar longo,"
    nvle "longo que parecia querer traspassar-lhe o coração."
    nvle " Olhar diabólico, olhar terrível, de que Nossa Senhora nos defenda,"
    nvle "a mim e a todos os bons cristãos."
    nvle "O riso murchou na boca de Antônio de Sousa."
    nvle "A gargalhada próxima a arrebentar ficou-lhe presa na garganta,"
    nvle "e ele sentiu o sangue gelar-se-lhe nas veias."
    nvle "O seu olhar sarcástico e curioso submeteu-se à"
    nvle "influência dos olhos da feiticeira."
    nvle "Quiçá pela primeira vez na vida soubesse então o que era medo."
    nvle "Mas não se mostrou vencido, que de rija têmpera de incredulidade era ele."
    nvle "Começou a dirigir motejos de toda espécie à velha,"
    nvle "que se retirava lentamente, curvada e trôpega,"
    nvle "parando de vez em quando e voltando para o moço o olhar amortecido."
    nvle "Este, conseguindo afinal soltar o riso,"
    nvle "dava gargalhadas nervosas que assustavam aos japiins"
    nvle "e afugentavam as rolas das moitas do cacaual."
    nvle "Louca e imprudente mocidade!"
    nvle "Quando a Maria Mucoim desapareceu por detrás dos cacaueiros,"
  
    play music "audio/detective.mp3"
    nvle "o Ribeiro tomou o braço do hóspede e obrigou-o a voltar para a casa."
    nvle "No caminho ainda deram alguns tiros, mas de caça nem sinal,"
    nvle "pois se em algum animal acertou o chumbo foi num dos melhores cães do Ribeiro,"
    nvle "que ficou muito penalizado e viu logo que aquilo era agouro."
    nvle "O Ribeiro, apesar das ladro-eiras que todos lhe atribuem,"
    nvle "é homem crente e de bastante siso."
    nvle "Quando chegaram à casa de vivenda,"
    nvle "seriam seis horas da tarde."
    nvle "Ribeiro exprobou com brandura ao amigo o que fizera à"
    nvle "feiticeira, mas o desgraçado rapaz riu-se,"
    nvle "dizendo que iria no dia seguinte visitar a tapuia."
    nvle "Debalde o dono do sítio tentou dissuadi-lo de tão louco projeto;"
    nvle "não o conseguiu."
    nvle "Era de mais a mais esse dia uma sexta-feira."
    nvle "Antônio de Sousa, depois de ter passado toda a manhã mui-to agitado,"
    nvle "armou-se de um terçado americano e abalou para o cacaual."
    nvle "A tarde estava feia. Nuvens cor de chumbo cobriam quase todo o céu"
    nvle "Um vento muito forte soprava do lado de cima,"
    nvle "e o rio corria com velocidade,"
    nvle "arrastando velhos troncos de cedro e periantãs"
    nvle "enormes onde as jaçanãs soltavam pios de aflição."
    nvle "As aningas esguias curvavam-se sobre as ribanceiras."
    nvle "Os galhos secos estalavam e uma multidão de folhas despegava-se"
    nvle "das árvores para voar ao sabor do vento."
    nvle "Os carneiros aproximavam-se do abrigo,"
    nvle "o gado mugia no curral, bandos de periquitos e de papagaios"
    nvle "cruzavam-se nos ares em grande algazarra."
    Estevao comum "De vez em quando, dentre as trêmulas aningas saía a voz solene do unicórnio. Procurando aninhar-se, as fétidas ciganas aumentavam com o grasnar corvino a grande agitação do rio, do campo e da floresta. "
    Estevao "diantavam os sapos dos atolei-ros e as rães dos capinzais"
    nvle "o seu concerto noturno alternando o canto desenxabido."
    nvle "Tudo isso viu e ouviu o tenente Sousa do meio do terreiro,"
    nvle "logo que transpôs a soleira da porta,"
    nvle "mas convencerá a um espírito forte a precisão dos agouros que nos fornece a maternal e franca natureza?"
    nvle "Antônio de Sousa internou-se resolutamente no cacaual."
    nvle "Passou sem parar nos sítios que lhe ficavam no caminho,"

    play sound "audio/latido.mp3"
    nvle "e os cães de guarda, saindo-lhe ao encontro,"
    nvle "não o conseguiram arrancar à profunda meditação em que caíra."
   
    scene bg cabaninha
    with dissolve
    play music "audio/dark forest.mp3"
    show tenente apreensivo
    with dissolve
    Tenente apreensivo "Então é nesse buraco que essa velha se entocou."
    nvle "Eram seis horas quando chegou à casa da Maria Mucoim,"
    nvle "situada entre terras incultas nos confins dos cacauais da margem esquerda."
    nvle "E, segundo dizem, um sítio horrendo e bem próprio de quem o habita."
    nvle "Numa palhoça miserável,"
    nvle "na narrativa de pessoas dignas de toda a consideração,"
    nvle "se passavam as cenas estranhas que firmaram"
    nvle "a reputação da antiga caseira do vigário."
    nvle "Já houve quem visse,"
    nvle "ao clarão de um grande incêndio que iluminava a tapera,"
    nvle "a Maria Mucoim dançando sobre a cumeeira danças diabólicas,"
    nvle "abraçada a um bode negro, coberto com um chapéu de três bicos,"
    nvle "tal qual como ultimamente usava o defunto padre."
    nvle "Alguém, ao passar por ali a desoras, ouviu o triste piar do murucututu,"
    nvle "ao passo que o sufocava um forte cheiro de enxofre."
    nvle "Alguns homens respeitáveis que por acaso se acharam"
    nvle "nos arredores da habitação maldita, depois de noite fechada, "
    nvle "sentiram tremer a terra sob os seus pés e ouviram a feiticeira berrar como uma cabra."
    nvle "A casa, pequena e negra,"
    nvle "compõe-se de duas peças sepa-radas por uma meia parede,"
    nvle "servindo de porta interior uma abertura redonda, tapada com um topé velho."
    nvle "A porta exte-rior é de japá, o teto de pindoba,"
    nvle "gasta pelo tempo, os esteios e caibros estão cheios de casas de cupim e de cabas."
    nvle "Sousa encontrou a velha sentada à soleira da porta,"
    nvle "com queixo metido nas mãos,"
    nvle "os cotovelos apoiados nas coxas,"
    nvle "com o olhar fito num bem-te-vi que cantava numa embaubeira."
    nvle "Sob a influência do olhar da velha,"
    nvle "o passarinho começou a agitar-se e a dar gritinhos aflitivos."
    nvle " A feiticeira não parecia dar pela presença do moço que lhe bateu familiarmente no ombro:"
    
    show tenente serio at left
    with dissolve
    show feiticeira seria at right
    with dissolve

    Tenente serio "Sou eu"
    Tenente "Lembra-se de ontem?"
    nvle "A velha não respondeu. Antônio de Sousa continuou depois de pequena pausa:"
    Tenente "Venho disposto a tirar a limpo as suas feitiçarias. Quero saber como foi que conseguiu enganar a toda esta vizinhança. Hei de conhecer os meios de que se serve"
    nvle "Maria Mucoim abaixou a cabeça, como para esconder um sorriso,"
    nvle "e com voz trêmula e arrastada, respondeu:"
    Feiticeira seria "Ora me deixe, branco. Vá-se embora, que é melhor."
    Tenente apreensivo "— Não saio daqui sem ver o que tem em casa."
    nvle "E o atrevido moço preparava-se para entrar na palhoça,"
    nvle "quando a velha,"
    nvle "erguendo-se de um jato,"
    nvle "impediu-lhe a passagem. Aquele corpo, curvado de ordinário, ficou direito e hirto."
    nvle "Os pequenos olhos, outrora amortecidos,"
    nvle "lançavam raios. Mas a voz continuou lenta e arrastada:"

    show feiticeira piscando at right
    with dissolve
    Feiticeira piscando "Não entre, branco, vá-se embora."
    nvle "Surpreso, o tenente Sousa estacou, mas, logo, recuperando a calma, riu-se"

    scene bg casebre
    with dissolve
    show feiticeira picandoinvetido
    with dissolve
    Feiticeira piscandoinvertido "Seu cabra idiota ignorante..."
    nvle "e penetrou na cabana. A feiticeira seguiu-o. Como nada visse o rapaz que lhe"
    nvle "atraísse a atenção no primeiro compartimento, avançou para o segundo,"
    nvle "separado daquele pela abertura redonda, tapada com um topé velho. Mas aí a"
    nvle "resistência que a tapuia ofereceu à sua ousadia foi muito mais séria. Colocou-se"
    nvle "de pé, crescida e tesa, à abertura da parede, e abriu os braços, para impedir-lhe"
    nvle "com o corpo a indiscreta visita. Esgotados os meios brandos, Antônio de Sousa"
    nvle "perdeu a cabeça, e, exasperado pelo sorriso horrendo da velha, pegou-a por um"
    nvle "braço, e, usando toda a força do seu corpo robusto, arrancou-a dali e atirou-a ao"
    nvle "meio da sala de entrada."
    nvle "A feiticeira foi bater com a fronte no chão, soltando gemidos lúgubres."
    nvle "Antônio arrancou a esteira que fechava a porta e penetrou no aposento, seguido"
    nvle "da velha, de rastos, pronunciando palavras, o dente negro num riso convulso e"
    nvle "asqueroso"

    play sound "audio/laught.mp3"
    nvle "Era um quarto singular o quarto de dormir de Maria Mucoim. Ao fundo,"
    nvle "uma rede rota e suja; um canto, um montão de ossos humanos; pousada nos"
    nvle "punhos da rede, uma coruja, branca como algodão, parecia dormir; e ao pé dela,"
    nvle "um gato preto descansava numa cama de palhas de milho. Sobre um banco"
    nvle "rústico, estavam várias panelas de forma estranha, e das traves do teto pendiam"
    nvle "cumbucas rachadas, donde escorria um líquido vermelho parecendo sangue. Um"
    nvle "enorme urubu, preso por uma embira ao esteio central do quarto, tentava picar"
    nvle "um grande bode, preto e barbado, que passeava solto, como se fora o dono da casa"

    nvle "A entrada de Antônio de Sousa causou um movimento geral. O murucututu"
    Feiticeira seria "Ahh seu branco desgraçado..."
    scene bg blood
    with dissolve
    play music "audio/creepy.mp3"
    Feiticeira piscando "Você vai ver o que é bom para tosse."
    nvle "entreabriu os olhos, bateu as asas e soltou um pio lúgubre. O gato pulou para a"
    nvle "rede, o bode recuou até ao fundo do quarto e arremeteu contra o visitante."
    nvle "Antônio, surpreendido pelo ataque, mal teve tempo de desviar o corpo, e foi logo"
    nvle "encostar-se parede, pondo-se em defesa com o terçado que trouxera."
    nvle "Foi então que, animada por gestos misteriosos da velha, a bicharia toda"
    nvle "avançou com uma fúria incrível. O gato correndo em roda do rapaz procurava"
    nvle "morder, fugindo sempre ao terçado. O urubu, solto como por encanto da corda"
    nvle "que o prendia, esvoaçava-lhe em torno da cabeça, querendo bicar-lhe os olhos."
    nvle "Parecia-lhe que se moviam os ossos humanos, amontoados a um canto, e que"
    nvle "das cumbucas corria sangue vivo."

    nvle "Antônio começou a arrepender-se da imprudência que cometera. Mas era"
    nvle "um valente moço, e o perigo lhe redobrava a coragem. Num lance certeiro"
    nvle "conseguiu ferir o bode no coração, ao mesmo tempo que dos lábios lhe saía"
    nvle "inconscientemente uma invocação religiosa"

    play sound "audio/danan.mp3"
    show tenente triste 
    with dissolve
    Tenente triste "Jesus, Maria!"
    nvle "O diabólico animal deu um berro formidável e foi recuando cair sem vida"
    nvle "sobre um monte de ossos; ao mesmo tempo o gato estorceu-se em convulsões"
    nvle "terríveis, e o urubu e a coruja fugiram pela porta aberta."
    nvle "A Mucoim, vendo o efeito daquelas palavras mágicas, soltou urros de fera e"
    nvle "atirou-se contra o tenente, procurando arrancar-lhe os olhos com as aguçadas"
    nvle "unhas. O moço agarrou-a pelos raros e amarelados cabelos e lançou-a contra o"
    nvle "esteio central. Depois fugiu, sim, fugiu, espavorido, aterrado. Ao transpor o"
    nvle "limiar, um grito o obrigou a voltar cabeça. A Maria Mucoim, deitada com os"
    nvle "peitos no chão e a cabeça erguida, cavava a terra com as unhas, arregaçava os"
    nvle "lábios roxos e delgados, e fitava no rapaz aquele olhar sem luz, aquele olhar que"
    nvle "parecia querer traspassar-lhe o coração."
    
    play music "audio/storm.mp3"
    play sound "audio/footsteps.mp3"
    scene bg florestasombria
    with dissolve
    nvle "O tenente Sousa, como se tivesse atrás de si o inferno todo, pôs-se a correr"
    nvle "pelos cacauais. Chovia a cântaros. Os medonhos trovões do Amazonas atroavam"
    nvle "os ares; de minuto em minuto relâmpagos rasgavam o céu. O rapaz corria. Os"
    nvle "galhos úmidos das árvores batiam-lhe no rosto. Os seus pés enterravam-se nas"
    nvle "folhas molhadas que tapetavam o solo. De quando em quando, ouvia o ruído da"
    nvle "queda das árvores feridas pelo raio ou derrubadas pelo vento, e cada vez mais"
    nvle "perto o uivo de uma onça faminta. A noite era escura. Só o guiava a luz"
    nvle "intermitente dos relâmpagos. Ora batia com cabeça em algum tronco de árvore,"
    nvle "ora os cipós amarravam-lhe as pernas, impedindo- lhe os passos"
    nvle "Mas ele ia prosseguindo sem olhar para trás, porque temia encontrar o"
    nvle "olhar da feiticeira, e estava certo de que o seguia uma legião de seres"
    nvle "misteriosos e horrendos."
    nvle "Quando chegou ao sítio do Ribeiro, molhado, roto, sem chapéu e sem"
    nvle "sapatos, todos dormiam na casa. Foi direto à porta do seu quarto, que dava para"
    nvle "a varanda, empurrou-a, entrou, e atirou-se ao fundo da rede, sem ânimo de"
    nvle "mudar de roupa. O desgraçado ardia em febre. Esteve muito tempo de olhos"
    nvle "abertos, mas em tal prostração que nem pensava, nem se movia. De repente,"
    nvle "ouviu um leve ruído por baixo da rede e despertou da espécie de letargo em que"
    nvle "caíra. Pôs um pé fora, procurando o chão, mas sentiu uma umidade. Olhou e viu"
    nvle "que o quarto estava alagado. Levantou-se apressado. A água vinha enchendo o"
    nvle "quarto, forçando a porta. Assustado, correu para fora"
    nvle "Um grito chegou-lhe aos ouvidos:"

    play sound "audio/mortalha.mp3"
    play music "audio/1907.mp3"
    nvle "— A cheia!"
    nvle "Um espetáculo assombroso ofereceu-se-lhe à vista. O Paranamiri"
    nvle "transbordava. O sítio do Ribeiro estava completamente inundado, e a casa"
    nvle "começava a sê-lo. Os cacauais, os aningais, as laranjeiras iam pouco a pouco"
    nvle "mergulhando. Bois, carneiros e cavalos boiavam ao acaso, e a cheia crescia"
    nvle "sempre. A água não tardou em dar-lhe pelos peitos. O delegado quis correr, mas"
    nvle "foi obrigado a nadar. A casa inundada parecia deserta, só se ouviam o ruído das"
    nvle "águas e, ao longe, aquela voz:"

    nvle "— A cheia!"
    nvle "Onde estariam o tenente Ribeiro e a família? Mortos? Teriam fugido"
    nvle "abandonando o hóspede à sua infeliz sorte? Onde salvar-se, se as águas cresciam"
    nvle "sempre, e o delegado já começava a sentir-se cansado de nadar. Nadava, nadava."
    nvle "As forças começavam a abandoná-lo, os braços recusavam-se ao serviço,"
    nvle "câimbras agudas lhe invadiam os pés e as pernas. Onde e como salvar-se?"
    nvle "De súbito viu aproximar-se uma luzinha e logo uma canoa, dentro da qual"
    nvle "lhe pareceu estar o tenente Ribeiro. Pelo menos era dele a voz que o chamava."

    show tenente triste
    with dissolve
    Tenente triste "Socorro!!!"
    nvle "gritou desesperado o Antônio de Sousa, e, juntando as forças"
    nvle "num violento esforço, nadou para montaria, salvação única que lhe restava, no"
    nvle "doloroso transe."
    stop sound fadeout 1.0

    nvle "Mas não era o tenente Ribeiro o tripulante da canoa. Acocorada à proa da"
    nvle "montaria, Maria Mucoim fitava-o com os olhos amortecidos, e aquele olhar sem"
    nvle "luz, que lhe queria traspassar o coração …"

    scene bg inicio
    with dissolve
    play music "audio/bossa.mp3"

    show silveira rindo at right
    with dissolve
    show estevao comum at left
    with dissolve

    Silveira rindo "HAHAHAH!"
    play sound "audio/critico.mp3"
    nvle "Uma gargalhada nervosa do Dr. Silveira interrompeu o velho Estêvão neste ponto da sua narrativa."

    return
